version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    depends_on:
      - db
      - phpmyadmin

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: mariadb:10.4
    container_name: db
    restart: unless-stopped
    command: --init-file /data/application/mediatheque.sql
    volumes:
      - ./mediatheque.sql:/data/application/mediatheque.sql
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    links:
      - db

volumes:
  mariadb-data:
